IGTI.PA.ArmazenamentoDescentralizado/Controllers/CadastrarAlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IGTI.PA.ArmazenamentoDescentralizado.Controllers
{
    public class CadastrarAlunoController : Controller
    {
        // GET: CadastrarAluno
        public ActionResult Index()
        {
            return View();
        }
    }
}

IGTI.PA.ArmazenamentoDescentralizado/Controllers/CadastrarCursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IGTI.PA.ArmazenamentoDescentralizado.Controllers
{
    public class CadastrarCursoController : Controller
    {
        // GET: CadastrarCurso
        public ActionResult Index()
        {
            return View();
        }
    }
}

IGTI.PA.ArmazenamentoDescentralizado/Controllers/CadastrarDisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IGTI.PA.ArmazenamentoDescentralizado.Controllers
{
    public class CadastrarDisciplinaController : Controller
    {
        // GET: CadastrarDisciplina
        public ActionResult Index()
        {
            return View();
        }
    }
}

IGTI.PA.ArmazenamentoDescentralizado/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IGTI.PA.ArmazenamentoDescentralizado.Controllers
{
    public class ProfessorController : Controller
    {
        // GET: Professor
        public ActionResult Index()
        {
            return View();
        }
    }
}

IGTI.PA.ArmazenamentoDescentralizado/Views/CadastrarCurso/Index.cshtml
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>
<!-- Header section -->
<header class="header-section" ng-cloak ng-controller="authenticationController as vm">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="site-logo">
                    <img height="140" src="~/Content/img/blockchain.jpg" alt="">
                </div>
                <div class="nav-switch">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
            <div class="col-lg-9 col-md-9">
                <a href="" class="site-btn header-btn" ng-click="vm.sair()">Sair</a>
                <nav class="main-menu">
                    <ul>
                        <li><a href="@Url.Action("Index", "Home" )">Home</a></li>
                        <li><a href="#">Sobre</a></li>
                        <li><a href="#">Cursos</a></li>
                        <li><a href="#">Novidade</a></li>
                        <li><a href="#">Contato</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- Header section end -->
<!-- Page info -->
<div ng-cloak ng-controller="cadastroCursoController as vm">
    <div class="set-bg" data-setbg="~/../Content/img/page-bg/1.jpg">
        <div class="container">
            <div class="site-breadcrumb" style="color:white; padding-left: 25px">
                <span style="color:white"> </span>
                <a href="@Url.Action("Index", "Professor")" ng-show="vm.usuarioLogado"><u>Upload</u></a>
                <a href="@Url.Action("Index", "CadastrarAluno" )" ng-show="vm.usuarioLogado"><u>Cadastrar aluno</u></a>
                <a href="@Url.Action("Index", "CadastrarCurso" )" ng-show="vm.usuarioLogado"><u>Cadastrar curso</u></a>
                <a href="@Url.Action("Index", "CadastrarDisciplina" )" ng-show="vm.usuarioLogado"><u>Registrar disciplina e nota</u></a>
                <span style="color:white;" class="pull-right">Professor: <span>{{vm.usuarioLogado}}</span></span>

            </div>
        </div>
    </div>
    <section class="signup-section spad">
        <div class="signup-bg set-bg" data-setbg="~/../Content/img/signup-bg.jpg"></div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="signup-warp">
                        <div class="section-title text-white text-left">
                            <h2>Cadastro curso</h2>
                        </div>
                        <!-- signup form -->
                        <form method="post" enctype="multipart/form-data" class="box has-advanced-upload signup-form">
                            <div class="progress" style="display: none;">
                                <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                    <span class="progressoAtual">0% complete</span>
                                </div>
                            </div>
                            <div>
                                <select class="form-control" ng-model="idCurso">
                                    <option>Aluno 1</option>
                                    <option>Aluno 2</option>
                                </select>
                            </div>

                            <input type="text" ng-model="nomeCurso" placeholder="Nome curso">

                            <label for="fileupload" class="file-up-btn" ng-click="vm.cadastrarCurso()">Salvar</label>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- signup section end -->
<script src="~/Scripts/app/conexaoMetaMask.js"></script>
<script src="~/Scripts/app/cadastrarCurso/cadastrarCursoController.js"></script>